## TCT Day 9 - Pandas cont' & Intro to numpy

* Pandas additional functions of interest  
    - select_dtypes
    - working with duplicates
    - append
    - sample
* Intro to json 
    - json normalize 
    - nested json 
* Intro to numpy

In [1]:
import pandas as pd

In [8]:
data=pd.read_excel('data.xlsx')

In [9]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket       Fare Cabin Embarked  
0      0         A/5 21171       7.25   NaN        S  
1      0          PC 17599  712833.00   C85        C  
2      0  STON/O2. 3101282    7925.00   NaN        S  
3      0            113803      53.10  C123        S  
4      0            373450       8.05   NaN        S

### dtypes

In [10]:
data.shape

(891, 12)

In [11]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [13]:
data.select_dtypes(include='int64')

PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [14]:
data.select_dtypes(include='number')

PassengerId  Survived  Pclass   Age  SibSp  Parch       Fare
0              1         0       3  22.0      1      0       7.25
1              2         1       1  38.0      1      0  712833.00
2              3         1       3  26.0      0      0    7925.00
3              4         1       1  35.0      1      0      53.10
4              5         0       3  35.0      0      0       8.05
..           ...       ...     ...   ...    ...    ...        ...
886          887         0       2  27.0      0      0      13.00
887          888         1       1  19.0      0      0      30.00
888          889         0       3   NaN      1      2      23.45
889          890         1       1  26.0      0      0      30.00
890          891         0       3  32.0      0      0       7.75

[891 rows x 7 columns]

In [15]:
data.select_dtypes(include='object')

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [16]:
data.select_dtypes(include=['float64','object'])

Name     Sex   Age  \
0                              Braund, Mr. Owen Harris    male  22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                               Heikkinen, Miss. Laina  female  26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                             Allen, Mr. William Henry    male  35.0   
..                                                 ...     ...   ...   
886                              Montvila, Rev. Juozas    male  27.0   
887                       Graham, Miss. Margaret Edith  female  19.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
889                              Behr, Mr. Karl Howell    male  26.0   
890                                Dooley, Mr. Patrick    male  32.0   

               Ticket       Fare Cabin Embarked  
0           A/5 21171       7.25   NaN        S  
1            PC 17599  712833.00   C85        C  
2    STON/O2. 3101282    7925.00   NaN        S  
3              113803      53.10  C123        S  
4              373450       8.05   NaN        S  
..                ...        ...   ...      ...  
886            211536      13.00   NaN        S  
887            112053      30.00   B42        S  
888        W./C. 6607      23.45   NaN        S  
889            111369      30.00  C148        C  
890            370376       7.75   NaN        Q  

[891 rows x 7 columns]

In [17]:
data.select_dtypes(exclude='int64')

Name     Sex   Age  \
0                              Braund, Mr. Owen Harris    male  22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                               Heikkinen, Miss. Laina  female  26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                             Allen, Mr. William Henry    male  35.0   
..                                                 ...     ...   ...   
886                              Montvila, Rev. Juozas    male  27.0   
887                       Graham, Miss. Margaret Edith  female  19.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
889                              Behr, Mr. Karl Howell    male  26.0   
890                                Dooley, Mr. Patrick    male  32.0   

               Ticket       Fare Cabin Embarked  
0           A/5 21171       7.25   NaN        S  
1            PC 17599  712833.00   C85        C  
2    STON/O2. 3101282    7925.00   NaN        S  
3              113803      53.10  C123        S  
4              373450       8.05   NaN        S  
..                ...        ...   ...      ...  
886            211536      13.00   NaN        S  
887            112053      30.00   B42        S  
888        W./C. 6607      23.45   NaN        S  
889            111369      30.00  C148        C  
890            370376       7.75   NaN        Q  

[891 rows x 7 columns]

### duplicates

In [18]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [19]:
data.Name.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [20]:
data.Name.duplicated().sum()

0

In [23]:
data.duplicated(subset=['Name','Cabin']).sum()

0

In [24]:
#exercise: duplicate a random row from the dataframe and run function duplicated()

#### append

In [27]:
my_list=data.iloc[100,:]

In [29]:
type(my_list)

pandas.core.series.Series

In [30]:
data.append(my_list,ignore_index=True)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   
891          101         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   
891                            Petranec, Miss. Matilda  female  28.0      0   

     Parch            Ticket       Fare Cabin Embarked  
0        0         A/5 21171       7.25   NaN        S  
1        0          PC 17599  712833.00   C85        C  
2        0  STON/O2. 3101282    7925.00   NaN        S  
3        0            113803      53.10  C123        S  
4        0            373450       8.05   NaN        S  
..     ...               ...        ...   ...      ...  
887      0            112053      30.00   B42        S  
888      2        W./C. 6607      23.45   NaN        S  
889      0            111369      30.00  C148        C  
890      0            370376       7.75   NaN        Q  
891      0            349245   78958.00   NaN        S  

[892 rows x 12 columns]

In [31]:
my_list

PassengerId                        101
Survived                             0
Pclass                               3
Name           Petranec, Miss. Matilda
Sex                             female
Age                               28.0
SibSp                                0
Parch                                0
Ticket                          349245
Fare                           78958.0
Cabin                              NaN
Embarked                             S
Name: 100, dtype: object

#### json

In [32]:
json_file=pd.read_json('simple.json')

In [33]:
json_file

id   name  math  physics  chemistry
0  A001    Tom    60       66         61
1  A002  James    89       76         51
2  A003  Jenny    79       90         78

In [35]:
json_file.to_json('simple1.json')

In [36]:
json_list = [
    { 
        'class': 'Year 1', 
        'student count': 20, 
        'room': 'Yellow',
        'info': {
            'teachers': { 
                'math': 'Rick Scott', 
                'physics': 'Elon Mask' 
            }
        },
        'students': [
            { 
                'name': 'Tom', 
                'sex': 'M', 
                'grades': { 'math': 66, 'physics': 77 } 
            },
            { 
                'name': 'James', 
                'sex': 'M', 
                'grades': { 'math': 80, 'physics': 78 } 
            },
        ]
    },
    { 
        'class': 'Year 2', 
        'student count': 25, 
        'room': 'Blue',
        'info': {
            'teachers': { 
                'math': 'Alan Turing', 
                'physics': 'Albert Einstein' 
            }
        },
        'students': [
            { 'name': 'Tony', 'sex': 'M' },
            { 'name': 'Jacqueline', 'sex': 'F' },
        ]
    },
]


In [37]:
pd.json_normalize(json_list)

class  student count    room  \
0  Year 1             20  Yellow   
1  Year 2             25    Blue   

                                            students info.teachers.math  \
0  [{'name': 'Tom', 'sex': 'M', 'grades': {'math'...         Rick Scott   
1  [{'name': 'Tony', 'sex': 'M'}, {'name': 'Jacqu...        Alan Turing   

  info.teachers.physics  
0             Elon Mask  
1       Albert Einstein

In [38]:
pd.json_normalize(json_list,record_path=['students'])

name sex  grades.math  grades.physics
0         Tom   M         66.0            77.0
1       James   M         80.0            78.0
2        Tony   M          NaN             NaN
3  Jacqueline   F          NaN             NaN

In [39]:
pd.json_normalize(json_list,record_path=['students'],meta=['class','room',['info','teachers','physics']])

name sex  grades.math  grades.physics   class    room  \
0         Tom   M         66.0            77.0  Year 1  Yellow   
1       James   M         80.0            78.0  Year 1  Yellow   
2        Tony   M          NaN             NaN  Year 2    Blue   
3  Jacqueline   F          NaN             NaN  Year 2    Blue   

  info.teachers.physics  
0             Elon Mask  
1             Elon Mask  
2       Albert Einstein  
3       Albert Einstein

In [40]:
new_json=pd.json_normalize(json_list,record_path=['students'],meta=['class','room',['info','teachers','physics']])

In [41]:
new_json.to_json('simple2.json')

In [42]:
new_json2=pd.read_json('simple2.json')
new_json2

name sex  grades.math  grades.physics   class    room  \
0         Tom   M         66.0            77.0  Year 1  Yellow   
1       James   M         80.0            78.0  Year 1  Yellow   
2        Tony   M          NaN             NaN  Year 2    Blue   
3  Jacqueline   F          NaN             NaN  Year 2    Blue   

  info.teachers.physics  
0             Elon Mask  
1             Elon Mask  
2       Albert Einstein  
3       Albert Einstein

In [43]:
import json

#### numpy

In [44]:
import numpy as np

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.ones(10).tolist()

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [49]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [50]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [51]:
np.array([1.,2,3,4,5.])

array([1., 2., 3., 4., 5.])

In [52]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.random.random(10)

array([0.46834605, 0.67039366, 0.54010348, 0.37401288, 0.60453085,
       0.31851064, 0.9346908 , 0.37369437, 0.26164171, 0.2010025 ])

In [58]:
np.random.randint(1,10,size=10)

array([7, 8, 1, 7, 4, 8, 3, 1, 8, 9])

In [59]:
my_array=np.arange(0,10,1)

In [61]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
my_array[0]

0

In [63]:
my_array[2:4]

array([2, 3])

In [64]:
my_array[0:4]

array([0, 1, 2, 3])

In [70]:
my_array[[-1]]

array([9])

In [67]:
my_array[-2:]

array([8, 9])

In [71]:
my_array.sum()

45

In [72]:
my_array.min()

0

In [73]:
my_array.max()

9

In [75]:
np.log(my_array)

<ipython-input-75-53bc6e9f5089>:1: RuntimeWarning: divide by zero encountered in log
  np.log(my_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [76]:
np.exp(my_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [77]:
#exercise: create two different arrays with random values and same size and try operations +, -, *,/

In [79]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
cond_list=[x<5,x>=5]
choice_list=[x,x**2]

In [81]:
np.select(cond_list,choice_list)

array([ 0,  1,  2,  3,  4, 25, 36, 49, 64, 81])

In [82]:
cond_list=[x<5,x>5]
choice_list=[x,x**2]

In [84]:
np.select(cond_list,choice_list,9999)

array([   0,    1,    2,    3,    4, 9999,   36,   49,   64,   81])

#### matrices

In [86]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
my_matrix=np.array([[1,2,3],[4,5,6]])

In [90]:
my_matrix[0,:]

array([1, 2, 3])

In [91]:
my_matrix[:,0]

array([1, 4])

In [92]:
my_matrix_2=my_matrix.copy()

In [93]:
my_matrix_2

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [97]:
x.reshape(3,5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [98]:
my_matrix_2

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
df_array=pd.DataFrame(my_matrix_2,columns=['one','two','three'],index=['one','two'])

In [106]:
df_array

one  two  three
one    1    2      3
two    4    5      6

#### sample

In [107]:
data.sample()

PassengerId  Survived  Pclass                         Name   Sex  Age  \
740          741         1       1  Hawksford, Mr. Walter James  male  NaN   

     SibSp  Parch Ticket  Fare Cabin Embarked  
740      0      0  16988  30.0   D45        S

In [108]:
data.sample(10)

PassengerId  Survived  Pclass  \
779          780         1       1   
704          705         0       3   
554          555         1       3   
251          252         0       3   
597          598         0       3   
688          689         0       3   
885          886         0       3   
40            41         0       3   
276          277         0       3   
333          334         0       3   

                                                  Name     Sex   Age  SibSp  \
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  female  43.0      0   
704                            Hansen, Mr. Henrik Juul    male  26.0      1   
554                                 Ohman, Miss. Velin  female  22.0      0   
251         Strom, Mrs. Wilhelm (Elna Matilda Persson)  female  29.0      1   
597                                Johnson, Mr. Alfred    male  49.0      0   
688                    Fischer, Mr. Eberhard Thelander    male  18.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0      1   
276                  Lindblom, Miss. Augusta Charlotta  female  45.0      0   
333                    Vander Planke, Mr. Leo Edmondus    male  16.0      2   

     Parch  Ticket        Fare Cabin Embarked  
779      1   24160  2113375.00    B3        S  
704      0  350025    78542.00   NaN        S  
554      0  347085     7775.00   NaN        S  
251      1  347054   104625.00    G6        S  
597      0    LINE        0.00   NaN        S  
688      0  350036    77958.00   NaN        S  
885      5  382652    29125.00   NaN        Q  
40       0    7546     9475.00   NaN        S  
276      0  347073        7.75   NaN        S  
333      0  345764       18.00   NaN        S

In [109]:
data.sample(10)

PassengerId  Survived  Pclass  \
95            96         0       3   
618          619         1       2   
889          890         1       1   
254          255         0       3   
835          836         1       1   
801          802         1       2   
442          443         0       3   
529          530         0       2   
286          287         1       3   
451          452         0       3   

                                            Name     Sex   Age  SibSp  Parch  \
95                   Shorney, Mr. Charles Joseph    male   NaN      0      0   
618                  Becker, Miss. Marion Louise  female   4.0      2      1   
889                        Behr, Mr. Karl Howell    male  26.0      0      0   
254     Rosblom, Mrs. Viktor (Helena Wilhelmina)  female  41.0      0      2   
835                  Compton, Miss. Sara Rebecca  female  39.0      1      1   
801  Collyer, Mrs. Harvey (Charlotte Annie Tate)  female  31.0      1      1   
442                    Petterson, Mr. Johan Emil    male  25.0      1      0   
529                  Hocking, Mr. Richard George    male  23.0      2      1   
286                      de Mulder, Mr. Theodore    male  30.0      0      0   
451              Hagland, Mr. Ingvald Olai Olsen    male   NaN      1      0   

         Ticket       Fare Cabin Embarked  
95       374910       8.05   NaN        S  
618      230136      39.00    F4        S  
889      111369      30.00  C148        C  
254      370129  202125.00   NaN        S  
835    PC 17756  831583.00   E49        C  
801  C.A. 31921      26.25   NaN        S  
442      347076    7775.00   NaN        S  
529       29104      11.50   NaN        S  
286      345774       9.50   NaN        S  
451       65303  199667.00   NaN        S